version: '3.7'
services:

  backend:
    build:
      context: ./backend
    container_name: identity-provider
    networks:
    - core
    - postgres
    env_file:
    - .env

  frontend:
    build:
      context: ./frontend
    container_name: login
    networks:
    - core

networks:
  core:
    name: core
  postgres:
    name: postgres